services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
        - ${PORT-BACK:-9000}:9000
        - ${PORT-FRONT:-8000}:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock